apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vllm-decode
  namespace: inference
spec:
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vllm-prefill
  namespace: inference
spec:
  maxReplicas: 1
